FROM tensorflow/tensorflow:2.8.0-gpu-jupyter

RUN set -x \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    git git lfs \    
  && rm -rf /var/lib/apt/lists/*

RUN pip install --use-feature=2020-resolver pandas elasticsearch-dsl elasticsearch matplotlib datashader bokeh holoviews panel tensorflow_probability tensorflow_hub transformers datasets[streaming] scikit-learn seaborn torch umap